### ISSUE TITLE
None záznamy nelze naimplementovat

### ISSUE THREAD

**Issue by kubaran11** [lukaskett/ochecklist-online-report#1]
Některé záznamy mi vyhodí chyby, že se program neprovede. Myslím, že jsou to ty nulové hodnoty z QE při dohlašování.

Příklad 1:
  - Runner:
      StartStatus: Started OK
      Id:          null
      Name:        ""
      Org:         ""
      Card:        null
      StartTime:   2023-08-04T13:29:00+02:00
      ClassName:   "H21E"
    ChangeLog:     null

Příklad 2:
  - Runner:
      NewCard:     8502727
      StartStatus: Started OK
      Id:          null
      Name:        ""
      Org:         ""
      Card:        null
      StartTime:   2023-08-04T13:09:00+02:00
      ClassName:   "D18A"
      Comment:     "Hana Malečková"
    ChangeLog:
      NewCard:     2023-08-04T13:08:50+02:00
      Comment:     2023-08-04T13:08:50+02:00

Traceback (most recent call last):
  File "C:\Users\42077\Downloads\ochecklist-online-report-main\process_ochecklist_report.py", line 631, in <module>
    main()
  File "C:\Users\42077\Downloads\ochecklist-online-report-main\process_ochecklist_report.py", line 17, in main
    generate_html_report(changes)
  File "C:\Users\42077\Downloads\ochecklist-online-report-main\process_ochecklist_report.py", line 446, in generate_html_report
    cards_changes_data += '''            
TypeError: can only concatenate str (not "NoneType") to str

Zkusil jsem tohle:
        for card in changes['changed_cards']:
            **if card[0] is None:
                card[0] = "prazdne"**

Na to mi to háže nějakou chybu s kódováním:
Traceback (most recent call last):
  File "C:\Users\42077\Downloads\ochecklist-online-report-main\process_ochecklist_report.py", line 628, in <module>
    main()
  File "C:\Users\42077\Downloads\ochecklist-online-report-main\process_ochecklist_report.py", line 15, in main
    downloaded_file = download_file_from_ftp(**ftp_server_credentials)
  File "C:\Users\42077\Downloads\ochecklist-online-report-main\process_ochecklist_report.py", line 47, in download_file_from_ftp
    ftp.retrbinary('RETR ' + filename, write_file_data)
  File "C:\Users\42077\AppData\Local\Programs\Python\Python39\lib\ftplib.py", line 434, in retrbinary
    callback(data)
  File "C:\Users\42077\Downloads\ochecklist-online-report-main\process_ochecklist_report.py", line 38, in write_file_data
    downloaded_file.write(data.decode('utf-8'))
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xc2 in position 1419: unexpected end of data

Možná jsem to způsobil tím, jak jsem ošetřil ten čip, tak tahle druhá chyba možná nemusí být relevantní.

Nenapadá tě, jak to snadno upravit tak, aby to běželo? Vždycky to nějak udělám, ale replace nějakých znaků není ideální způsob...

YAML soubor: https://drive.google.com/file/d/1WS-ICNyvaGqXebuytxFfdJHXAyeh_VLF/view?usp=sharing

**Comment by lukaskett** [comment]
Mrknu na to večer a dám vědět. Touhle použití "na dohlášky" mě vůbec nenapadlo a přitom je tak logický.
